### PR TITLE
Some minor corrections to en-GB language file

### PR DESCRIPTION
**Pull request by ptopenweb**

### CODE REVIEW

**Comment by danyj** [comment]
Thank you much for the fixes , But you did not have to go the extra mile for spaces before the =.

**Comment by ptopenweb** [comment]
:) ok. No problem.

**Comment by danyj** [comment]
This will be published in next release. For now is in master. Do me a favor and retest if you have time. Thank you!

**Comment by ptopenweb** [comment]
Yes it works fine

**Pull request merged**
