### PR TITLE
Corrected bug: PHP AJAX messages in multilanguage [3]

### PR DESCRIPTION
**Pull request by ptopenweb**
Needs to know the current language so it can show the messages in other languages, if not, only english.

### CODE REVIEW

**Comment by ptopenweb** [comment]
with are the others wrong?
They are different files...

**Comment by danyj** [comment]
they are missing the translation
https://github.com/ptopenweb/yjsg/commit/d5e39b2c88c537b8e5ce94f98b9b14d10d00df4e#diff-28359853619a6ed8bf92587a36e6faf0R193

https://github.com/ptopenweb/yjsg/commit/1bb9ae7de75cbde14d390071356e0253fdb90e4f#diff-a4bfeb670f705ae409f7d19dd0cde22aR424


This one is correct 
https://github.com/ptopenweb/yjsg/commit/b19b82a8343abd3307ffb6e7eee55417707dd63a#diff-09d2054a40ee7665febeea747efdb9e3R35

Have you tested on 2.5 ?

**Comment by ptopenweb** [comment]
Missing? No
They are in the other pull request that is one standby
https://github.com/YJSGframework/yjsg/pull/18/files#diff-a4bfeb670f705ae409f7d19dd0cde22aL422
https://github.com/YJSGframework/yjsg/pull/18/files#diff-28359853619a6ed8bf92587a36e6faf0L191

**Comment by ptopenweb** [comment]
I don't have a 2.5 installation to test.

**Comment by danyj** [comment]
OK , will reopen those 2. Everything must be tested on 2.5 first , they are many members who did not upgrade to 3.x , we cant leave them out.

**Comment by ptopenweb** [comment]
ok i understand that. Please do test in 2.5.
I try allways to do the changes in "legacy" (for 2.5? or for old yjsg?) folder too, but i never know.

**Comment by danyj** [comment]
OK bud , did you commit to your repo changes? 
I need to get your master in order to test everything without merging and your git does not have those changes
https://github.com/YJSGframework/yjsg/blob/master/elements/yjsgupdate.php#L422

legacy folder is not 2.5 , legacy is for templates made before yjsg plugin.

**Comment by danyj** [comment]
cratch previous comment, I had wrong tab open

**Comment by ptopenweb** [comment]
will close these 3 pulls and merge to my master so they go in the other pull request

**Pull request closed without merging**
